Repository openkruise/openkruise.io, pull requests merged in 2021-12, with the labels that each got.

#14 Update docs for features in v1.0
  docs/core-concepts/inplace-update.md
  docs/user-manuals/containerlaunchpriority.md
  docs/user-manuals/resourcedistribution.md
  i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/inplace-update.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/containerlaunchpriority.md
Labels: size/M, approved

#15 Add blogs for releases 0.9.0 and 0.10.0
  blog/2021-05-20-release-0.9.0.md
  blog/2021-09-06-release-0.10.0.md
  i18n/zh/docusaurus-plugin-content-blog/2021-05-20-release-0.9.0.md
  i18n/zh/docusaurus-plugin-content-blog/2021-09-06-release-0.10.0.md
  src/css/custom.css
Labels: size/XL, approved

#17 Improve blog v1.0
  blog/2021-12-13-release-1.0.md
  i18n/zh/docusaurus-plugin-content-blog/2021-12-13-release-1.0.md
Labels: size/S, approved

#18 Update community
  docusaurus.config.js
Labels: size/XS, approved

#19 Add wechat invitation png
  static/img/wechat-invitation.png
Labels: size/XS, approved

#22 Fix typo and zero space
  blog/2021-12-13-release-1.0.md
  docs/introduction.md
  i18n/zh/code.json
  src/components/HomepageFeatures.js
  src/pages/index.js
  versioned_docs/version-v0.10/introduction.md
  versioned_docs/version-v1.0/introduction.md
Labels: size/M, approved

#24 Test commit
  .gitignore
Labels: approved

#25 Enable jsdelivr CDN
  .github/workflows/documentation.yaml
Labels: size/S, approved

#26 Fix typo
  i18n/zh/docusaurus-plugin-content-blog/2021-12-13-release-1.0.md
Labels: size/XS, approved

#27 Update cloneset.md
  docs/user-manuals/cloneset.md
Labels: lgtm, size/XS, approved

#29 Add WorkloadSpread Blog
  blog/2021-09-22-workloadspread.md
  blog/authors.yml
  i18n/zh/docusaurus-plugin-content-blog/2021-09-22-workloadspread.md
  static/img/blog/2021-09-22-workloadspread/arch.jpg
  static/img/blog/2021-09-22-workloadspread/case-1.jpg
  static/img/blog/2021-09-22-workloadspread/case-2.jpg
  static/img/blog/2021-09-22-workloadspread/case-3.jpg
  static/img/blog/2021-09-22-workloadspread/case-4.jpg
Labels: size/XL, lgtm, approved

#31 Fix titles and image of WorkloadSpread blog
  blog/2021-09-22-workloadspread.md
  i18n/zh/docusaurus-plugin-content-blog/2021-09-22-workloadspread.md
  static/img/blog/2021-09-22-workloadspread/case-3.jpg
Labels: lgtm, size/XS, approved

#32 Fix image for ImagePullJob
  static/img/docs/user-manuals/imagepulling.png
Labels: size/XS, approved

#33 blog: OpenKruise 0.8.0, A Powerful Tool for Sidecar Container Management; OpenKruise 0.9.0, SidecarSet Helps Mesh Container Hot Upgrade
  blog/2021-03-15-sidecarSet-0.8.0.md
  blog/2021-06-10-sidecarset-hot-update-0.9.0.md
  blog/authors.yml
  i18n/zh/docusaurus-plugin-content-blog/2021-03-15-sidecarSet-0.8.0.md
  i18n/zh/docusaurus-plugin-content-blog/2021-06-10-sidecarset-hot-update-0.9.0.md
  static/img/blog/2021-03-15-sidecarset/inject_sidecar.png
  static/img/blog/2021-03-15-sidecarset/inplace_sidecar.png
  static/img/blog/2021-03-15-sidecarset/logsidecar.png
  static/img/blog/2021-06-10-sidecarset-hot-update/how_update_mesh.png
  static/img/blog/2021-06-10-sidecarset-hot-update/inject_sidecar.png
  static/img/blog/2021-06-10-sidecarset-hot-update/migration.png
  static/img/blog/2021-06-10-sidecarset-hot-update/update_sidecar.png
Labels: size/XL, lgtm, approved

#34 Show all blogs
  docusaurus.config.js
Labels: approved

#35 Update podunavailablebudget.md
  docs/user-manuals/podunavailablebudget.md
Labels: lgtm, size/XS, approved
