Repository openkruise/openkruise.io, pull requests merged in 2021-11, with the labels that each got.

#8 Update v0.10.1 and v1.0.0-alpha.2
  docs/installation.md
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10.json
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/best-practices/hpa-configuration.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/core-concepts/architecture.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/developer-manuals/go-client.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/developer-manuals/java-client.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/developer-manuals/other-languages.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/faq.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/introduction.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/advancedcronjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/advanceddaemonset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/advancedstatefulset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/cloneset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/containerrecreaterequest.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/deletionprotection.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/podunavailablebudget.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/uniteddeployment.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/workloadspread.md
  versioned_docs/version-v0.10/best-practices/hpa-configuration.md
  versioned_docs/version-v0.10/core-concepts/architecture.md
  versioned_docs/version-v0.10/developer-manuals/go-client.md
  versioned_docs/version-v0.10/developer-manuals/java-client.md
  versioned_docs/version-v0.10/developer-manuals/other-languages.md
  versioned_docs/version-v0.10/faq.md
  versioned_docs/version-v0.10/installation.md
  versioned_docs/version-v0.10/introduction.md
  versioned_docs/version-v0.10/user-manuals/advancedcronjob.md
  versioned_docs/version-v0.10/user-manuals/advanceddaemonset.md
  versioned_docs/version-v0.10/user-manuals/advancedstatefulset.md
  versioned_docs/version-v0.10/user-manuals/broadcastjob.md
  versioned_docs/version-v0.10/user-manuals/cloneset.md
  versioned_docs/version-v0.10/user-manuals/containerrecreaterequest.md
  versioned_docs/version-v0.10/user-manuals/deletionprotection.md
  versioned_docs/version-v0.10/user-manuals/imagepulljob.md
  versioned_docs/version-v0.10/user-manuals/podunavailablebudget.md
  versioned_docs/version-v0.10/user-manuals/sidecarset.md
  versioned_docs/version-v0.10/user-manuals/uniteddeployment.md
  versioned_docs/version-v0.10/user-manuals/workloadspread.md
  versioned_sidebars/version-v0.10-sidebars.json
  versions.json
Labels: size/M

#9 Add ResourceDistribution Doc
  docs/user-manuals/resourcedistribution.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/resourcedistribution.md
  sidebars.js
Labels: size/L, lgtm

#11 Update v1.0.0-beta.0
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
Labels: size/S, approved

#12 Add ScaleStrategy.MaxUnavailable docs for CloneSet
  docs/user-manuals/cloneset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
Labels: size/M, lgtm, approved

#13 fix sidecarset sample
  docs/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/sidecarset.md
  versioned_docs/version-v0.10/user-manuals/sidecarset.md
Labels: approved
