Repository openkruise/openkruise.io, pull requests merged in 2022-02, with the labels that each got.

#40 modify best practices gitops
  docs/best-practices/gitops-with-kruise.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/gitops-with-kruise.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/gitops-with-kruise.md
  versioned_docs/version-v1.0/best-practices/gitops-with-kruise.md
Labels: size/M, lgtm, approved

#42 test update README
  README.md
Labels: lgtm, size/XS, approved

#43 Add tips for installation on EKS
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/installation.md
  versioned_docs/version-v1.0/installation.md
Labels: size/S, lgtm, approved
