Repository openkruise/openkruise.io, pull requests merged in 2022-01, with the labels that each got.

#38 Fix kruise-api version
  docs/developer-manuals/go-client.md
  i18n/zh/docusaurus-plugin-content-docs/current/developer-manuals/go-client.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/developer-manuals/go-client.md
  versioned_docs/version-v1.0/developer-manuals/go-client.md
Labels: size/XS, approved

#36 gitops with kruise
  blog/2021-03-15-sidecarSet-0.8.0.md
  blog/2021-06-10-sidecarset-hot-update-0.9.0.md
  docs/best-practices/gitops-with-kruise.md
  i18n/zh/docusaurus-plugin-content-blog/2021-03-15-sidecarSet-0.8.0.md
  i18n/zh/docusaurus-plugin-content-blog/2021-06-10-sidecarset-hot-update-0.9.0.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/gitops-with-kruise.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/gitops-with-kruise.md
  sidebars.js
  static/img/docs/best-practices/argo_sync_healthy.png
  static/img/docs/best-practices/argo_sync_unknown.png
  static/img/docs/best-practices/argocd.jpeg
  static/img/docs/best-practices/git_envs.png
  static/img/docs/best-practices/guestbook.png
  versioned_docs/version-v1.0/best-practices/gitops-with-kruise.md
  versioned_sidebars/version-v1.0-sidebars.json
Labels: size/XL, lgtm, approved

#37 Add WorkloadSpread best practice -- Extreme Elastic Schedule Solution Based on HPA
  docs/best-practices/elastic-deployment.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/elastic-deployment.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/best-practices/elastic-deployment.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/elastic-deployment.md
  sidebars.js
  static/img/docs/user-manuals/elasticd-deployment-arch.jpg
  static/img/docs/user-manuals/elasticd-deployment-show-0.gif
  static/img/docs/user-manuals/elasticd-deployment-show-1.gif
  static/img/docs/user-manuals/elasticd-deployment-show-2.gif
  static/img/docs/user-manuals/elasticd-deployment-show-3.gif
  versioned_docs/version-v0.10/best-practices/elastic-deployment.md
  versioned_docs/version-v1.0/best-practices/elastic-deployment.md
  versioned_sidebars/version-v0.10-sidebars.json
  versioned_sidebars/version-v1.0-sidebars.json
Labels: size/XXL, lgtm, approved

#39 Update version 1.0.1
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/installation.md
  versioned_docs/version-v1.0/installation.md
Labels: size/M, approved
