Repository openkruise/openkruise.io, pull requests merged in 2022-09, with the labels that each got.

#71 Fix name of released project
  blog/2022-06-07-release-1.2.md
Labels: lgtm, size/XS, approved

#70 pod probe marker docs
  docs/user-manuals/podprobemarker.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/podprobemarker.md
  sidebars.js
Labels: size/L, lgtm, approved

#73 Add TimeZone into acj doc
  docs/user-manuals/advancedcronjob.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advancedcronjob.md
Labels: size/S, lgtm, approved

#74 Add scaling with PreparingDelete in CloneSet doc
  docs/user-manuals/cloneset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
Labels: size/M, lgtm, approved

#75 Add PreDownloadImageForDaemonSetUpdate featureGate into doc
  docs/user-manuals/advanceddaemonset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advanceddaemonset.md
Labels: size/M, lgtm, approved

#72 Add SidecarSet and WorkloadSpread docs for 1.3.0
  docs/user-manuals/sidecarset.md
  docs/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/workloadspread.md
Labels: size/M, lgtm, approved
