Repository openkruise/openkruise.io, pull requests merged in 2022-03, with the labels that each got.

#44 best practice: ci+image pre-download
  docs/best-practices/ci-pipeline-image-predownload.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/ci-pipeline-image-predownload.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/ci-pipeline-image-predownload.md
  sidebars.js
  static/img/docs/best-practices/ci_cd_pipeline.png
  static/img/docs/best-practices/helloworld.png
  static/img/docs/best-practices/imagepulljob.png
  static/img/docs/best-practices/tekton_pipeline.png
  versioned_docs/version-v1.0/best-practices/ci-pipeline-image-predownload.md
  versioned_sidebars/version-v1.0-sidebars.json
Labels: size/XXL, lgtm, approved

#46 Cloud-Native Devops Best Practices(2) - GitOps + OpenKruise CloneSet
  docs/best-practices/gitops-with-kruise.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/gitops-with-kruise.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/gitops-with-kruise.md
  static/img/docs/best-practices/argo_sync_unknown.png
  static/img/docs/best-practices/git_envs.png
  static/img/docs/best-practices/guestbook.png
  versioned_docs/version-v1.0/best-practices/gitops-with-kruise.md
Labels: size/XXL, lgtm, approved

#47 Update architecture image
  static/img/docs/core-concepts/architecture.graffle
  static/img/docs/core-concepts/architecture.png
Labels: size/XS

#48 Add two best practices: CloneSet Lifecycle, ACronJob+BroadcastJob
  .gitignore
  docs/best-practices/acronjob+broadcastjob.md
  docs/best-practices/cloneset-lifecycle.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/acronjob+broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/cloneset-lifecycle.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/acronjob+broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/cloneset-lifecycle.md
  sidebars.js
  static/img/docs/best-practices/cloneset_lifecycle.png
  versioned_docs/version-v1.0/best-practices/acronjob+broadcastjob.md
  versioned_docs/version-v1.0/best-practices/cloneset-lifecycle.md
  versioned_sidebars/version-v1.0-sidebars.json
Labels: size/XXL, lgtm, approved

#49 Adjust the sidebar of best practices
  sidebars.js
  versioned_sidebars/version-v1.0-sidebars.json
Labels: lgtm, size/XS, approved

#51 Fix custom css for blog title
  docusaurus.config.js
  src/css/custom.css
Labels: size/XS

#52 Fix custom css for blog title
  docusaurus.config.js
  src/css/custom.css
Labels: size/M

#53 fix `Edit this page` in blog
  docusaurus.config.js
Labels: lgtm, size/XS, approved
