Repository openkruise/openkruise.io, pull requests merged in 2022-12, with the labels that each got.

#84 fix sidecarset ControllerRevision doc
  blog/2022-10-07-release-1.3.md
  docs/best-practices/gitops-with-kruise.md
  docs/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-blog/2022-10-07-release-1.3.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/sidecarset.md
  versioned_docs/version-v1.0/best-practices/gitops-with-kruise.md
  versioned_docs/version-v1.1/best-practices/gitops-with-kruise.md
  versioned_docs/version-v1.3/user-manuals/sidecarset.md
Labels: size/S, lgtm, approved

#87 change hangzhou repo to shanghai
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/installation.md
  versioned_docs/version-v0.10/installation.md
  versioned_docs/version-v1.0/installation.md
  versioned_docs/version-v1.1/installation.md
  versioned_docs/version-v1.2/installation.md
  versioned_docs/version-v1.3/installation.md
Labels: size/M, lgtm, approved

#89 Sidecarset doc fix
  docs/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/sidecarset.md
  versioned_docs/version-v1.3/user-manuals/sidecarset.md
Labels: lgtm, size/XS, approved
