Repository openkruise/openkruise.io, pull requests merged in 2022-07, with the labels that each got.

#63 Fix typo of introduction
  docs/introduction.md
  versioned_docs/version-v0.10/introduction.md
  versioned_docs/version-v1.0/introduction.md
  versioned_docs/version-v1.1/introduction.md
  versioned_docs/version-v1.2/introduction.md
Labels: size/S, lgtm, approved

#65 Update the installation doc to the latest version `1.2.0`
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/installation.md
  versioned_docs/version-v0.10/installation.md
  versioned_docs/version-v1.0/installation.md
  versioned_docs/version-v1.1/installation.md
  versioned_docs/version-v1.2/installation.md
Labels: size/M, lgtm, approved

#67 Update 'controller.kubernetes.io/pod-deletion-cost' url
  docs/user-manuals/cloneset.md
Labels: lgtm, size/XS, approved

#68 Fix doc of BroadcastJob from `BackoffLimit` to `RestartLimit`
  docs/user-manuals/broadcastjob.md
Labels: size/M, lgtm, approved
