Repository openkruise/openkruise.io, pull requests merged in 2022-06, with the labels that each got.

#58 persistent pod state and pub support custom workload docs
  docs/user-manuals/persistentpodstate.md
  docs/user-manuals/podunavailablebudget.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/persistentpodstate.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/podunavailablebudget.md
  sidebars.js
  static/img/docs/user-manuals/persistent-pod-state.png
  static/img/docs/user-manuals/static-ip.png
Labels: size/L, lgtm, approved

#59 Fix workflow action yaml
  .github/workflows/documentation.yaml
  src/css/custom.css
Labels: size/S

#60 update cloneset statefulset daemonset docs for kruise 1.2.0
  docs/user-manuals/advanceddaemonset.md
  docs/user-manuals/advancedstatefulset.md
  docs/user-manuals/cloneset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advanceddaemonset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/advancedstatefulset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
Labels: size/L, lgtm, approved

#62 typo fix: dependencies
  docs/introduction.md
Labels: lgtm, size/XS, approved
