Repository openkruise/openkruise.io, pull requests merged in 2023-07, with the labels that each got.

#113 Fix: specify code format
  docs/user-manuals/imagepulljob.md
  docs/user-manuals/persistentpodstate.md
  docs/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/persistentpodstate.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/persistentpodstate.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/persistentpodstate.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/imagepulljob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/persistentpodstate.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/sidecarset.md
  versioned_docs/version-v0.10/user-manuals/imagepulljob.md
  versioned_docs/version-v0.10/user-manuals/sidecarset.md
  versioned_docs/version-v1.0/user-manuals/imagepulljob.md
  versioned_docs/version-v1.0/user-manuals/sidecarset.md
  versioned_docs/version-v1.1/user-manuals/imagepulljob.md
  versioned_docs/version-v1.1/user-manuals/sidecarset.md
  versioned_docs/version-v1.2/user-manuals/imagepulljob.md
  versioned_docs/version-v1.2/user-manuals/persistentpodstate.md
  versioned_docs/version-v1.2/user-manuals/sidecarset.md
  versioned_docs/version-v1.3/user-manuals/imagepulljob.md
  versioned_docs/version-v1.3/user-manuals/persistentpodstate.md
  versioned_docs/version-v1.3/user-manuals/sidecarset.md
  versioned_docs/version-v1.4/user-manuals/imagepulljob.md
  versioned_docs/version-v1.4/user-manuals/persistentpodstate.md
  versioned_docs/version-v1.4/user-manuals/sidecarset.md
Labels: size/L, lgtm, approved

#115 remove dependency
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/installation.md
  kruisegame/installation.md
  kruisegame/user-manuals/gameservers-scale.md
Labels: size/M, lgtm, approved

#116 add other settings for gameserver auto-scaling
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/gameservers-scale.md
  kruisegame/installation.md
  kruisegame/user-manuals/gameservers-scale.md
Labels: size/S, lgtm, approved
