Repository openkruise/openkruise.io, pull requests merged in 2023-04, with the labels that each got.

#96 Add job sidecar terminator and cloneset prenormal hook docs
  docs/user-manuals/cloneset.md
  docs/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/cloneset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/jobsidecarterminator.md
  sidebars.js
  static/img/docs/user-manuals/cloneset-lifecycle.png
  versioned_docs/version-v1.4/user-manuals/cloneset.md
  versioned_docs/version-v1.4/user-manuals/jobsidecarterminator.md
  versioned_sidebars/version-v1.4-sidebars.json
Labels: size/L, lgtm, approved

#98 fix: wrong link for sidecarset in in-place update doc
  docs/core-concepts/inplace-update.md
Labels: lgtm, size/XS, approved

#99 disable feature-gate PreDownloadImageForInPlaceUpdate
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/installation.md
  versioned_docs/version-v1.4/installation.md
Labels: lgtm, size/XS, approved

#97 fix Indentation problem of tekton pipeline yaml file
  docs/best-practices/ci-pipeline-image-predownload.md
Labels: lgtm, size/XS, approved

#100 add kruise game doc
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current.json
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/design-concept.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/developer-manuals/contribution.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/developer-manuals/faq.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/introduction.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/container-startup-sequence-control.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/deploy-gameservers.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/gameservers-scale.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/hot-update.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/network.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/service-qualities.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/update-strategy.md
  kruisegame/design-concept.md
  kruisegame/developer-manuals/contribution.md
  kruisegame/developer-manuals/faq.md
  kruisegame/installation.md
  kruisegame/introduction.md
  kruisegame/user-manuals/container-startup-sequence-control.md
  kruisegame/user-manuals/deploy-gameservers.md
  kruisegame/user-manuals/gameservers-scale.md
  kruisegame/user-manuals/hot-update.md
  kruisegame/user-manuals/network.md
  kruisegame/user-manuals/service-qualities.md
  kruisegame/user-manuals/update-strategy.md
  sidebars-kruisegame.js
  static/img/kruisegame/arch.png
  static/img/kruisegame/intro.png
  static/img/kruisegame/logo.png
  static/img/kruisegame/user-manuals/hot-update.png
  static/img/kruisegame/user-manuals/update-priority.png
  static/img/kruisegame/user-manuals/warning-ding.png
  static/img/kruisegame/workload.png
  yarn.lock
Labels: size/XXL, lgtm, approved

#101 fix kruise-game doc
  docusaurus.config.js
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/design-concept.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/developer-manuals/faq.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/introduction.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/hot-update.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/service-qualities.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/update-strategy.md
  i18n/zh/docusaurus-theme-classic/navbar.json
  kruisegame/developer-manuals/faq.md
  kruisegame/introduction.md
  kruisegame/user-manuals/network.md
  package-lock.json
  package.json
  yarn.lock
Labels: size/XXL, lgtm, approved

#103 kruise v1.4 blog
  blog/2023-04-18-release-1.4.md
  i18n/zh/docusaurus-plugin-content-blog/2023-04-18-release-1.4.md
  rollouts/user-manuals/api-specifications.md
  rollouts/user-manuals/strategy-ab-testing.md
Labels: size/L, lgtm, approved

#105 correct labels for version dropdown
  README.md
  i18n/zh/docusaurus-plugin-content-docs/current.json
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10.json
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1.json
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2.json
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3.json
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4.json
Labels: size/M, lgtm, approved
