Repository openkruise/openkruise.io, pull requests merged in 2023-09, with the labels that each got.

#124 [Fix] sidecarset docs typo
  blog/2021-03-15-sidecarSet-0.8.0.md
  i18n/zh/docusaurus-plugin-content-blog/2021-03-15-sidecarSet-0.8.0.md
Labels: size/S, lgtm, approved

#129 [FIX] jobsidecarterminator typo
  i18n/zh/docusaurus-plugin-content-blog/2023-04-18-release-1.4.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/jobsidecarterminator.md
Labels: size/S, lgtm, approved

#127 [FIX] remove BackoffLimit
  docs/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/broadcastjob.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/broadcastjob.md
  versioned_docs/version-v0.10/user-manuals/broadcastjob.md
  versioned_docs/version-v1.0/user-manuals/broadcastjob.md
  versioned_docs/version-v1.1/user-manuals/broadcastjob.md
  versioned_docs/version-v1.2/user-manuals/broadcastjob.md
  versioned_docs/version-v1.3/user-manuals/broadcastjob.md
  versioned_docs/version-v1.4/user-manuals/broadcastjob.md
Labels: size/M, lgtm, approved

#130 [Fix] ADD KRUISE_TERMINATE_SIDECAR ENV priority description
  blog/2023-04-18-release-1.4.md
  docs/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-blog/2023-04-18-release-1.4.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/jobsidecarterminator.md
  versioned_docs/version-v1.4/user-manuals/jobsidecarterminator.md
Labels: size/S, lgtm, approved

#134 [FIX] workloadspread yaml format error
  docs/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/workloadspread.md
  versioned_docs/version-v0.10/user-manuals/workloadspread.md
  versioned_docs/version-v1.0/user-manuals/workloadspread.md
  versioned_docs/version-v1.1/user-manuals/workloadspread.md
  versioned_docs/version-v1.2/user-manuals/workloadspread.md
  versioned_docs/version-v1.3/user-manuals/workloadspread.md
  versioned_docs/version-v1.4/user-manuals/workloadspread.md
  versioned_docs/version-v1.5/user-manuals/workloadspread.md
Labels: size/L, lgtm, approved

#132 [FIX] workloadspread `` error
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/workloadspread.md
Labels: lgtm, size/XS, approved

#135 [fix] matchExpressions retract
  docs/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/workloadspread.md
  versioned_docs/version-v0.10/user-manuals/workloadspread.md
  versioned_docs/version-v1.0/user-manuals/workloadspread.md
  versioned_docs/version-v1.1/user-manuals/workloadspread.md
  versioned_docs/version-v1.2/user-manuals/workloadspread.md
  versioned_docs/version-v1.3/user-manuals/workloadspread.md
  versioned_docs/version-v1.4/user-manuals/workloadspread.md
  versioned_docs/version-v1.5/user-manuals/workloadspread.md
Labels: size/L, lgtm, approved

#138 OKG add user wuduan
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/introduction.md
  kruisegame/introduction.md
  static/img/kruisegame/wuduan-logo.png
Labels: lgtm, size/XS, approved

#139 [FIX] link click error
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/podprobemarker.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/podprobemarker.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/podprobemarker.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/podprobemarker.md
Labels: size/S, lgtm, approved
