Repository openkruise/openkruise.io, pull requests merged in 2023-12, with the labels that each got.

#150 Add 1.5.1 docs
  .github/workflows/diff.py
  .github/workflows/go.mod
  .github/workflows/go.sum
  docs/installation.md
  docs/user-manuals/uniteddeployment.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/uniteddeployment.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/uniteddeployment.md
  versioned_docs/version-v1.5/installation.md
  versioned_docs/version-v1.5/user-manuals/uniteddeployment.md
Labels: size/L, lgtm, approved

#151 kruise rollout v0.5.0
  rollouts/best-practices/traffic-routing-istio-api.md
  rollouts/developer-manuals/custom-network-provider.md
  rollouts/installation.md
  rollouts/user-manuals/api-specifications.md
  rollouts/user-manuals/basic-usage.md
  rollouts/user-manuals/strategy-ab-testing.md
  rollouts/user-manuals/strategy-canary-update.md
  rollouts/user-manuals/strategy-multi-batch-update.md
  sidebars-rollouts.js
  src/css/custom.css
Labels: size/XL, lgtm, approved

#152 kruise-game users add wanglong & lbdj
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/introduction.md
  kruisegame/introduction.md
  static/img/kruisegame/wanglong-logo.png
  static/img/kruisegame/xingchao-logo.png
Labels: lgtm, size/XS, approved

#153 kruise game Dashboard
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/game-dashboard.md
  kruisegame/user-manuals/game-dashboard.md
  sidebars-kruisegame.js
  static/img/kruisegame/user-manuals/dash-begin-install.png
  static/img/kruisegame/user-manuals/dash-gs-jump.png
  static/img/kruisegame/user-manuals/dash-gs-ops.png
  static/img/kruisegame/user-manuals/dash-gs-opsState-updated.png
  static/img/kruisegame/user-manuals/dash-gs-update-opsState.png
  static/img/kruisegame/user-manuals/dash-gs.png
  static/img/kruisegame/user-manuals/dash-gss-jump.png
  static/img/kruisegame/user-manuals/dash-gss-ops.png
  static/img/kruisegame/user-manuals/dash-gss.png
  static/img/kruisegame/user-manuals/dash-installed.png
  static/img/kruisegame/user-manuals/dash-mainpage.png
  static/img/kruisegame/user-manuals/dash-management.png
  static/img/kruisegame/user-manuals/dash-okg.png
  static/img/kruisegame/user-manuals/dash-ops.png
  static/img/kruisegame/user-manuals/dash-overview.jpg
  static/img/kruisegame/user-manuals/dash-version-select.png
Labels: size/L, lgtm, approved

#154 fix rollout api version
  rollouts/user-manuals/api-specifications.md
Labels: lgtm, size/XS, approved
