Repository openkruise/openkruise.io, pull requests merged in 2024-06, with the labels that each got.

#187 add blogs and videoes for kruise-game
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/blog-video/ack-one-okg.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/blog-video/cloud-forward-okg.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/blog-video/okg-911.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/blog-video/okg-gsshosting.md
  kruisegame/blog-video/ack-one-okg.md
  kruisegame/blog-video/cloud-forward-okg.md
  kruisegame/blog-video/okg-911.md
  kruisegame/blog-video/okg-gsshosting.md
  sidebars-kruisegame.js
  static/img/kruisegame/blog-video/okg-911.png
  static/img/kruisegame/blog-video/okg-gsshosting.png
Labels: size/M, lgtm, approved

#188 add site verification file for future seo usage
  static/BingSiteAuth.xml
  static/baidu_verify_codeva-MxM3lNwVIQ.html
  static/google232dc131ec8a2e94.html
Labels: lgtm, size/XS, approved

#177 fix: correct the SidecarTerminator feature gate name
  .github/workflows/diff.py
  .github/workflows/pre_dict.json
  docs/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/jobsidecarterminator.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/user-manuals/jobsidecarterminator.md
  versioned_docs/version-v1.4/user-manuals/jobsidecarterminator.md
  versioned_docs/version-v1.5/user-manuals/jobsidecarterminator.md
  versioned_docs/version-v1.6/user-manuals/jobsidecarterminator.md
Labels: size/XXL, lgtm, approved

#189 fix log sidecar container docs
  docs/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/current/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/best-practices/log-container-sidecarset.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/best-practices/log-container-sidecarset.md
  versioned_docs/version-v1.0/best-practices/log-container-sidecarset.md
  versioned_docs/version-v1.1/best-practices/log-container-sidecarset.md
  versioned_docs/version-v1.2/best-practices/log-container-sidecarset.md
  versioned_docs/version-v1.3/best-practices/log-container-sidecarset.md
  versioned_docs/version-v1.4/best-practices/log-container-sidecarset.md
  versioned_docs/version-v1.5/best-practices/log-container-sidecarset.md
  versioned_docs/version-v1.6/best-practices/log-container-sidecarset.md
Labels: size/XXL, lgtm, approved
