Repository openkruise/openkruise.io, pull requests merged in 2024-04, with the labels that each got.

#175 kruise 1.6.2
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/version-v0.2.1/installation.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/version-v0.3.0/installation.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/version-v0.4.1/installation.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/version-v0.5.0/installation.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/version-v0.6.1/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/installation.md
  versioned_docs/version-v1.4/installation.md
  versioned_docs/version-v1.5/installation.md
  versioned_docs/version-v1.6/installation.md
Labels: size/M, lgtm, approved

#176 fix: WorkloadSpread supported obj
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v0.10/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.0/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.1/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.2/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.3/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.4/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.5/user-manuals/workloadspread.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/user-manuals/workloadspread.md
  versioned_docs/version-v0.10/user-manuals/workloadspread.md
  versioned_docs/version-v1.0/user-manuals/workloadspread.md
  versioned_docs/version-v1.1/user-manuals/workloadspread.md
  versioned_docs/version-v1.2/user-manuals/workloadspread.md
Labels: size/S, lgtm, approved

#174 Update podprobemarker.md
  docs/user-manuals/podprobemarker.md
Labels: lgtm, size/XS, approved

#173 update rollback user-manual for rollout
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/basic-usage.md
  rollouts/user-manuals/basic-usage.md
Labels: size/M, lgtm, approved

#178 add cri version notice in installation
  .github/workflows/pre_dict.json
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/installation.md
  versioned_docs/version-v1.6/installation.md
Labels: size/S, lgtm, approved

#179 kruise 1.6.3
  docs/installation.md
  i18n/zh/docusaurus-plugin-content-docs/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.6/installation.md
  versioned_docs/version-v1.6/installation.md
Labels: size/S, lgtm, approved
