Repository openkruise/openkruise.io, pull requests merged in 2024-05, with the labels that each got.

#182 Best Practices for Agile Delivery and Operations Management of Gaming…
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/best-practices/gameserver-delivery-management.md
  kruisegame/best-practices/gameserver-delivery-management.md
  sidebars-kruisegame.js
  static/img/kruisegame/best-practices/argo.png
  static/img/kruisegame/best-practices/git1.png
  static/img/kruisegame/best-practices/git2.png
Labels: size/L, lgtm, approved

#183 add OKG users
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/introduction.md
  kruisegame/introduction.md
  static/img/kruisegame/baibian-logo.png
  static/img/kruisegame/chillyroom-logo.png
  static/img/kruisegame/gsshosting-logo.png
  static/img/kruisegame/lilith-logo.png
Labels: size/M, lgtm, approved

#185 fix image repository
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/installation.md
  kruisegame/installation.md
Labels: lgtm, size/XS, approved

#186 fix the example format issue on rollout
  rollouts/user-manuals/strategy-multi-batch-update.md
Labels: lgtm, size/XS, approved
