Repository openkruise/openkruise.io, pull requests merged in 2024-08, with the labels that each got.

#199 add users of OKG
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/introduction.md
  kruisegame/introduction.md
  static/img/kruisegame/360-logo.png
  static/img/kruisegame/bekko-logo.png
  static/img/kruisegame/vma-logo.png
  static/img/kruisegame/yahaha-logo.png
  static/img/kruisegame/yostar-logo.png
Labels: size/M, lgtm, approved

#197 Fix incorrect translations, data, and punctuation
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/best-practices/traffic-routing-istio-api.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/basic-usage.md
  rollouts/best-practices/traffic-routing-istio-api.md
Labels: size/S, lgtm, approved

#202 update docs of okg dashboard 2.0
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/game-dashboard.md
  kruisegame/user-manuals/game-dashboard.md
  static/img/kruisegame/user-manuals/dash-addresource.png
  static/img/kruisegame/user-manuals/dash-config.png
  static/img/kruisegame/user-manuals/dash-deployunit.png
  static/img/kruisegame/user-manuals/dash-gs-project.png
  static/img/kruisegame/user-manuals/dash-gss-project.png
  static/img/kruisegame/user-manuals/dash-project.png
Labels: size/L, lgtm, approved
