Repository openkruise/openkruise.io, pull requests merged in 2024-07, with the labels that each got.

#191 add end to end canary update doc
  .github/workflows/pre_dict.json
  docs/user-manuals/cloneset.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/strategy-end2end-canary-update.md
  i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/cloneset.md
  package-lock.json
  rollouts/user-manuals/strategy-end2end-canary-update.md
  static/img/rollouts/e2e.png
  yarn.lock
Labels: size/XXL, lgtm, approved

#190 add more details for kruise-game CRD
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/crd-field-description.md
  kruisegame/user-manuals/crd-field-description.md
Labels: size/M, lgtm, approved

#192 Add user yongshi for OKG
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/introduction.md
  kruisegame/introduction.md
  static/img/kruisegame/yongshi-logo.png
Labels: lgtm, size/XS, approved

#193 add more doc about end to end canary update
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/introduction.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/api-specifications.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/strategy-multi-batch-update.md
  rollouts/introduction.md
  rollouts/user-manuals/api-specifications.md
  rollouts/user-manuals/strategy-ab-testing.md
  rollouts/user-manuals/strategy-multi-batch-update.md
  sidebars-rollouts.js
Labels: size/L, lgtm, approved

#194 okg add best practice for workflow
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/best-practices/workflow.md
  kruisegame/best-practices/workflow.md
  sidebars-kruisegame.js
Labels: size/L, lgtm, approved

#195 Ensure GITHUB_TOKEN has permission id-token: write
  .github/workflows/documentation.yaml
Labels: lgtm, size/XS, approved

#196 add doc for gracePeriodSeconds
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/api-specifications.md
  rollouts/user-manuals/api-specifications.md
Labels: size/S, lgtm, approved
