Repository openkruise/openkruise.io, pull requests merged in 2024-02, with the labels that each got.

#161 client-go doc
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/developer-manuals/go-client.md
  kruisegame/developer-manuals/go-client.md
  sidebars-kruisegame.js
Labels: size/L, lgtm, approved

#162 fix kruise-game doc
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/best-practices/pve-game.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/developer-manuals/go-client.md
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/network.md
  kruisegame/best-practices/pve-game.md
  kruisegame/developer-manuals/go-client.md
  kruisegame/user-manuals/network.md
Labels: size/S, lgtm, approved

#164 update rollout docs in Chinese
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current.json
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/best-practices/traffic-routing-istio-api.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/developer-manuals/custom-network-provider.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/installation.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/introduction.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/api-specifications.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/basic-usage.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/strategy-ab-testing.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/strategy-canary-update.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/strategy-multi-batch-update.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/version-v0.4.1/installation.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/version-v0.4.1/introduction.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/version-v0.4.1/user-manuals/api-specifications.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/version-v0.4.1/user-manuals/basic-usage.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/version-v0.4.1/user-manuals/strategy-ab-testing.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/version-v0.4.1/user-manuals/strategy-canary-update.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/version-v0.4.1/user-manuals/strategy-multi-batch-update.md
  rollouts/developer-manuals/custom-network-provider.md
  rollouts/introduction.md
  rollouts/user-manuals/api-specifications.md
  rollouts/user-manuals/basic-usage.md
Labels: size/XXL, lgtm, approved

#165 add best practice of shm for gameservers
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/best-practices/shared-mem.md
  kruisegame/best-practices/shared-mem.md
  sidebars-kruisegame.js
  static/img/kruisegame/best-practices/shm-arch.png
  static/img/kruisegame/best-practices/shm-gs-log.png
  static/img/kruisegame/best-practices/shm-host-ipcs.png
  static/img/kruisegame/best-practices/shm-init-log.png
Labels: size/L, lgtm, approved

#166 kruise game add docs for dns mechanism
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/deploy-gameservers.md
  kruisegame/user-manuals/deploy-gameservers.md
Labels: size/L, lgtm, approved
