Repository openkruise/openkruise.io, pull requests merged in 2025-07, with the labels that each got.

#250 Operator guide
  .github/workflows/pre_dict.json
  docs/installation.md
  docs/operator-manuals/availability.md
  docs/operator-manuals/troubleshooting.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/api-specifications.md
  i18n/zh/docusaurus-plugin-content-docs-rollouts/current/user-manuals/basic-usage.md
  i18n/zh/docusaurus-plugin-content-docs/current.json
  i18n/zh/docusaurus-plugin-content-docs/current/operator-manuals/availability.md
  i18n/zh/docusaurus-plugin-content-docs/current/operator-manuals/troubleshooting.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7.json
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/operator-manuals/availability.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.7/operator-manuals/troubleshooting.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8.json
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/operator-manuals/availability.md
  i18n/zh/docusaurus-plugin-content-docs/version-v1.8/operator-manuals/troubleshooting.md
  rollouts/user-manuals/api-specifications.md
  rollouts/user-manuals/basic-usage.md
  sidebars.js
  versioned_docs/version-v1.7/operator-manuals/availability.md
  versioned_docs/version-v1.7/operator-manuals/troubleshooting.md
  versioned_docs/version-v1.8/operator-manuals/availability.md
  versioned_docs/version-v1.8/operator-manuals/troubleshooting.md
  versioned_sidebars/version-v1.7-sidebars.json
  versioned_sidebars/version-v1.8-sidebars.json
Labels: size/XXL, lgtm, approved

#254 Fix search functionality
  docusaurus.config.js
Labels: lgtm, size/XS, approved

#255 Enhance github action security
  .github/workflows/documentation.yaml
  docusaurus.config.js
Labels: size/S, lgtm, approved

#258 fix github pages environment
  .github/workflows/documentation.yaml
  .gitignore
Labels: lgtm, size/XS, approved

#257 Add Adopters and Supporters sections to openkruise website
  docusaurus.config.js
  i18n/zh/code.json
  i18n/zh/docusaurus-theme-classic/navbar.json
  src/components/SupportersSection.js
  src/components/SupportersSection.module.css
  src/data/adopters.js
  src/pages/adopters.js
  src/pages/adopters.module.css
  src/pages/index.js
Labels: size/XL, lgtm, approved

#259 fix github pages environment and crawler problem
  docusaurus.config.js
Labels: lgtm, size/XS, approved

#260 reenable contextual search
  docusaurus.config.js
Labels: lgtm, size/XS, approved

#263 fix(ui): Improve GitHub icon visibility in dark mode
  src/css/custom.css
Labels: lgtm, size/XS, approved

#261 Improvements as per reviewers feedback
  i18n/zh/docusaurus-theme-classic/footer.json
  src/components/SupportersSection.js
  src/components/SupportersSection.module.css
  src/data/adopters.js
Labels: size/XL, lgtm, approved

#264 Enable native dependency caching in workflows
  .github/workflows/documentation.yaml
Labels: lgtm, size/XS, approved

#266 Removed the duplicate editUrl property
  docusaurus.config.js
Labels: lgtm, size/XS, approved

#246 update TencentCloud-CLB plugin
  i18n/zh/docusaurus-plugin-content-docs-kruisegame/current/user-manuals/network.md
  kruisegame/user-manuals/network.md
Labels: size/M, lgtm, approved

#268 doc: remove incompatible field
  blog/2025-02-19-elastic-components.md
  i18n/zh/docusaurus-plugin-content-blog/2025-02-19-elastic-components.md
Labels: lgtm, size/XS, approved

#267 Added comprehensive new questions in FAQ covering all major aspects
  docs/faq.md
Labels: size/L
